'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {createServer}=require('./server'),schema=require('./schema.json');
const root=path.resolve(__dirname,'../../.autodev/card-studio-v2');
async function run(){
 await fs.mkdir(root,{recursive:true});const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const url=process.env.CARD_STUDIO_V2_URL||`http://127.0.0.1:${server.address().port}/card-studio-v2/`;
 let browser;const checks=[],errors=[],requests=[];
 try{
  browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  const page=await context.newPage();page.setDefaultTimeout(9000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({method:r.method(),url:r.url()}));
  await page.goto(url);await page.locator('#save-state').filter({hasText:'端末のDBに接続'}).waitFor();
  await page.screenshot({path:path.join(root,'welcome-desktop.png'),fullPage:true});
  await page.locator('[data-template="defense"]').click();
  assert.equal(await page.getByLabel('被ダメージ倍率',{exact:true}).inputValue(),'0.7');
  assert.equal(await page.locator('[data-bind$=".amount.mode"]').count(),0);
  await page.getByLabel('被ダメージ倍率',{exact:true}).fill('0.6');
  await page.getByLabel('持続ターン数',{exact:true}).fill('3');
  await page.getByLabel('付与する状態',{exact:true}).selectOption('stealth');
  assert.equal(await page.getByLabel('被ダメージ倍率',{exact:true}).count(),0);
  assert.equal(await page.getByLabel('持続ターン数',{exact:true}).inputValue(),'2');
  await page.getByLabel('付与する状態',{exact:true}).selectOption('armorRatio');
  assert.equal(await page.getByLabel('被ダメージ倍率',{exact:true}).inputValue(),'0.6');
  assert.equal(await page.getByLabel('持続ターン数',{exact:true}).inputValue(),'3');
  checks.push('状態専用フォーム、非表示値保持、専用期間の復元');
  await page.getByLabel('付与する状態',{exact:true}).selectOption('poison');
  assert.equal(await page.getByLabel('持続ターン数',{exact:true}).inputValue(),'3');
  await page.getByLabel('付与する状態',{exact:true}).selectOption('contactPoison');
  assert.equal(await page.getByLabel('与える毒の期間',{exact:true}).inputValue(),'3');
  assert.equal(await page.getByLabel('持続ターン数',{exact:true}).inputValue(),'2');
  await page.getByLabel('与える毒の期間',{exact:true}).fill('4');
  checks.push('毒の既定3T、接触毒と毒の二つの期間');
  await page.getByLabel('付与する状態',{exact:true}).selectOption('guardShare');
  await page.getByRole('button',{name:'＋ 守る対象を設定',exact:true}).click();
  const protectedGroup=page.locator('fieldset').filter({has:page.locator('legend').filter({hasText:'守る対象'})}).last();
  await protectedGroup.locator('[data-preset="allyFront"]').click();
  await page.getByLabel('保持者が肩代わりする割合',{exact:true}).fill('0.5');
  assert.match(await page.locator('#preview').innerText(),/味方3マス/);
  await page.screenshot({path:path.join(root,'guard-desktop.png'),fullPage:true});
  checks.push('守護対象と保護役を別々に入力');
  await page.getByLabel('種類',{exact:true}).selectOption('attack');
  await page.locator('[data-preset="lowHP"]').first().click();
  assert.equal(await page.getByLabel('異なる対象を選ぶ数',{exact:true}).inputValue(),'1');
  await page.getByLabel('異なる対象を選ぶ数',{exact:true}).fill('2');
  await page.getByLabel('指定方法',{exact:true}).selectOption('area');
  assert.equal(await page.getByLabel('異なる対象を選ぶ数',{exact:true}).count(),0);
  await page.getByLabel('指定方法',{exact:true}).selectOption('search');
  assert.equal(await page.getByLabel('異なる対象を選ぶ数',{exact:true}).inputValue(),'2');
  await page.locator('[data-bind="card.skills.front.effects.0.target.filter.kind"]').selectOption('stat');
  assert.equal(await page.locator('[data-bind="card.skills.front.effects.0.target.filter.subject"]').count(),0);
  await page.getByLabel('閾値',{exact:true}).fill('30');
  checks.push('範囲とサーチの分岐、条件保持、候補主体固定');
  const effectDetails=page.locator('[data-open-key="card.skills.front.effects.0.details"]');await effectDetails.locator(':scope > summary').click();
  await page.getByLabel('対象固定の攻撃回数',{exact:true}).fill('3');
  await page.getByLabel('対象選びからの繰り返し',{exact:true}).fill('2');
  await page.locator('[data-open-key="skill.front.details"] > summary').click();
  await page.getByLabel('行動全体の繰り返し',{exact:true}).fill('4');
  await page.locator('[data-action="add-effect"]').click();assert.equal(await page.locator('[data-action="add-effect"]').isDisabled(),true);
  await page.getByRole('button',{name:'効果2を上へ',exact:true}).click();
  assert.equal(await page.locator('[data-effect-index="1"] [data-bind$=".attackCount"]').inputValue(),'3');
  checks.push('対象数・連撃・効果反復・行動反復の独立と並べ替え');
  await page.locator('[data-slot="ultimate"]').click();await page.getByLabel('なし／組み立てる',{exact:true}).selectOption('custom');
  for(let i=0;i<3;i++)await page.locator('[data-action="add-effect"]').click();assert.equal(await page.locator('[data-effect-index]').count(),3);assert.equal(await page.locator('[data-action="add-effect"]').isDisabled(),true);
  await page.locator('[data-slot="alpha"]').click();await page.getByLabel('なし／組立／登録済み',{exact:true}).selectOption('custom');
  assert.equal(await page.getByLabel('発動イベント（必須）',{exact:true}).locator('option[value="inherit"]').count(),0);await page.getByLabel('発動イベント（必須）',{exact:true}).selectOption('turnStart');
  checks.push('必殺3効果、α最上位時点の明示');
  await page.locator('[data-tab="basic"]').click();await page.getByLabel('カード名',{exact:true}).fill('森の護衛者');await page.getByLabel('分類',{exact:true}).selectOption('plant');await page.getByLabel('得意地形 森',{exact:true}).check();
  await page.getByLabel('HP',{exact:true}).fill('140');
  await page.locator('[data-open-key="card.details"] > summary').click();await page.getByLabel('枚数制限区分',{exact:true}).fill('2');await page.getByRole('button',{name:'初期配置禁止マス 左前衛',exact:true}).click();
  await page.locator('#art-file').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aKXcAAAAASUVORK5CYII=','base64')});
  await page.locator('.art-box img').waitFor();await page.locator('[data-action="clear-art"]').click();
  await page.locator('[data-tab="traits"]').click();await page.getByRole('button',{name:'＋ 特性を追加',exact:true}).click();await page.getByLabel('登録済み特性',{exact:true}).selectOption('armored');await page.getByLabel('軽減量',{exact:true}).fill('8');
  await page.locator('[data-tab="notes"]').click();await page.getByLabel('設計メモ',{exact:true}).fill('防御フォームと二段階反復を確認');
  await page.locator('#save').click();await page.locator('#save-state').filter({hasText:'保存済み'}).waitFor();
  await page.reload();await page.getByLabel('カード名',{exact:true}).waitFor();assert.equal(await page.getByLabel('カード名',{exact:true}).inputValue(),'森の護衛者');assert.equal(await page.getByLabel('HP',{exact:true}).inputValue(),'140');
  checks.push('18項目、画像、特性専用値、メモ、保存・再読込');
  const exportWait=page.waitForEvent('download');await page.locator('[data-action="export"]').click();const dbDownload=await exportWait;const db=JSON.parse(await fs.readFile(await dbDownload.path(),'utf8'));assert.equal(db.format,'card-studio-v2-library');assert.equal(db.cards[0].card.skills.front.effects[1].attackCount,3);assert.equal(db.cards[0].card.traits[0].params.cut,8);
  const other=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const page2=await other.newPage();page2.on('pageerror',e=>errors.push(e.message));await page2.goto(url);await page2.locator('#save-state').filter({hasText:'接続'}).waitFor();await page2.locator('#json-file').setInputFiles({name:'db.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(db))});await page2.getByLabel('カード名',{exact:true}).waitFor();assert.equal(await page2.getByLabel('HP',{exact:true}).inputValue(),'140');await page2.locator('#save').click();await page2.locator('#save-state').filter({hasText:'保存済み'}).waitFor();
  checks.push('独立端末へJSON受渡し');
  const brokenSchema=JSON.parse(JSON.stringify(schema));brokenSchema.forms.card=brokenSchema.forms.card.filter(r=>r.key!=='name');
  await page.locator('#schema-file').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(brokenSchema))});await page.locator('#notice').filter({hasText:'必須の入力定義'}).waitFor();assert.equal(await page.getByLabel('カード名',{exact:true}).inputValue(),'森の護衛者');
  const brokenDB=JSON.parse(JSON.stringify(db));brokenDB.cards[0].card={};
  await page.locator('#json-file').setInputFiles({name:'broken-db.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(brokenDB))});await page.locator('#notice').filter({hasText:'行動枠が不足'}).waitFor();assert.equal(await page.getByLabel('カード名',{exact:true}).inputValue(),'森の護衛者');
  checks.push('壊れた定義・カードDBを拒否し現用入力を保持');
  const legacy={schemaVersion:1,revision:0,cards:[{id:'legacy',card:{name:'旧版の原文'},notes:{intent:'旧メモ'},history:[{text:'履歴'}]}],definitions:[],abilityIdeas:[{id:'idea',text:'自然言語のまま'}]};
  await page.locator('#json-file').setInputFiles({name:'v1.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await page.locator('#archives').click();
  const archiveWait=page.waitForEvent('download');await page.locator('[data-archive="0"]').click();assert.deepEqual(JSON.parse(await fs.readFile(await(await archiveWait).path(),'utf8')),legacy);await page.getByRole('button',{name:'閉じる',exact:true}).click();
  checks.push('旧版DBの原本往復保持');
  const extended=JSON.parse(JSON.stringify(schema));extended.definitions.state.armorRatio.label='軽量装甲（入力確認）';extended.forms['state.armorRatio'][0].label='軽減後のダメージ倍率';
  await page.locator('#schema-file').setInputFiles({name:'schema.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(extended))});await page.getByRole('button',{name:'この定義を適用',exact:true}).click();await page.locator('[data-tab="effects"]').click();await page.locator('[data-slot="front"]').click();await page.locator('[data-effect-index="0"]').getByLabel('種類',{exact:true}).selectOption('status');await page.locator('[data-effect-index="0"]').getByLabel('付与する状態',{exact:true}).selectOption('armorRatio');await page.getByLabel('軽減後のダメージ倍率',{exact:true}).fill('0.7');
  checks.push('定義JSON変更をフォームへ反映');
  const largeContext=await browser.newContext({acceptDownloads:true});const largePage=await largeContext.newPage();largePage.on('pageerror',e=>errors.push(e.message));await largePage.goto(url);await largePage.locator('#save-state').filter({hasText:'接続'}).waitFor();
  const largeDB=JSON.parse(JSON.stringify(db));largeDB.cards[0].notes='x'.repeat(26*1024*1024);await largePage.locator('#json-file').setInputFiles({name:'large-db.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(largeDB))});await largePage.getByLabel('カード名',{exact:true}).waitFor();
  const largeWait=largePage.waitForEvent('download');await largePage.locator('[data-action="export"]').click();const largeRoundTrip=JSON.parse(await fs.readFile(await(await largeWait).path(),'utf8'));assert.equal(largeRoundTrip.cards[0].notes.length,26*1024*1024);await largeContext.close();checks.push('25MiBを超えるDBの取込・書出し');
  for(const [name,width,height]of [['desktop',1440,1000],['tablet',820,1100],['mobile',390,844],['small',320,740]]){
   await page.setViewportSize({width,height});await page.locator('[data-tab="basic"]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' basic overflow');await page.screenshot({path:path.join(root,'basic-'+name+'.png'),fullPage:true});
   await page.locator('[data-tab="effects"]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' effects overflow');await page.screenshot({path:path.join(root,'effects-'+name+'.png'),fullPage:true});
  }checks.push('1440/820/390/320px 基本・効果の操作と横はみ出しなし');
  await page.locator('#save').click();await page.locator('#save-state').filter({hasText:'保存済み'}).waitFor();
  const stale=await context.newPage();await stale.goto(url);await stale.getByLabel('カード名',{exact:true}).waitFor();
  await page.locator('[data-tab="basic"]').click();await page.getByLabel('カード名',{exact:true}).fill('最新保存');await page.locator('#save').click();await page.locator('#save-state').filter({hasText:'保存済み'}).waitFor();
  await stale.getByLabel('カード名',{exact:true}).fill('競合中の入力');await stale.locator('#save').click();await stale.locator('#notice').filter({hasText:'別のタブ'}).waitFor();assert.equal(await stale.getByLabel('カード名',{exact:true}).inputValue(),'競合中の入力');checks.push('競合時に上書きを拒否し編集中の入力を保持');
  const oldPage=await context.newPage();await oldPage.goto(new URL('../card-studio/',url).href);await oldPage.locator('#save-state').filter({hasText:'接続'}).waitFor();await oldPage.locator('[data-template="attack"]').click();await oldPage.getByLabel('カード名',{exact:true}).fill('旧版を保持');await oldPage.locator('#save').click();await oldPage.locator('#save-state').filter({hasText:'保存済み'}).waitFor();await page.reload();await page.getByLabel('カード名',{exact:true}).waitFor();assert.equal(await page.getByLabel('カード名',{exact:true}).inputValue(),'最新保存');await oldPage.reload();await oldPage.getByLabel('カード名',{exact:true}).waitFor();assert.equal(await oldPage.getByLabel('カード名',{exact:true}).inputValue(),'旧版を保持');checks.push('新旧UI・IndexedDBの独立');
  assert.deepEqual(errors,[]);assert.ok(!requests.some(r=>r.method!=='GET'));checks.push('ブラウザ例外なし・データ送信なし');
  const report={url,checks,errors,date:new Date().toISOString()};await fs.writeFile(path.join(root,process.env.CARD_STUDIO_V2_URL?'publication.json':'browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
