'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const os=require('node:os');
const {createServer}=require('./server');
const M=require('./model');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');

(async()=>{
  const dataDir=await fs.mkdtemp(path.join(os.tmpdir(),'card-studio-browser-'));
  const artifactDir=path.join(__dirname,'data','verification');await fs.mkdir(artifactDir,{recursive:true});
  const server=createServer({dataDir});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const url=`http://127.0.0.1:${server.address().port}`;
  let browser;const errors=[];const checks=[];
  try {
    browser=await chromium.launch({channel:'msedge',headless:true});
    const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,acceptDownloads:true});
    const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
    await page.goto(url);await page.locator('#save-state').filter({hasText:'接続'}).waitFor();
    await page.locator('[data-template="support"]').click();
    await page.getByLabel('カード名',{exact:true}).fill('苔庭の守り手');
    await page.getByLabel('AT',{exact:true}).fill('40');
    await page.locator('[data-terrain="森"]').check();await page.locator('[data-terrain="海"]').check();
    await page.locator('[data-action="add-trait"]').click();
    await page.locator('[data-bind="card.traits.0.definitionId"]').selectOption('armored');
    await page.locator('[data-bind="card.traits.0.value"]').fill('5');
    await page.locator('[data-bind="card.traits.0.effectAmount"]').fill('AT×1.0');
    await page.locator('#art-file').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aKXcAAAAASUVORK5CYII=','base64')});
    await page.locator('.art-input img').waitFor();
    assert.equal(await page.locator('.terrain-icons button').count(),2);
    await page.getByRole('button',{name:'装甲の説明',exact:true}).click();assert.match(await page.locator('#dialog-body').textContent(),/ダメージカット/);assert.match(await page.locator('#dialog-body').textContent(),/AT×1.0/);await page.keyboard.press('Escape');
    await page.locator('.terrain-icons button').first().click();assert.match(await page.locator('#dialog-body').textContent(),/森・海/);await page.keyboard.press('Escape');
    checks.push('基本情報・複数地形・特性説明・画像アップロード');
    await page.locator('[data-action="clear-art"]').click();
    await page.locator('[data-tab="effects"]').click();await page.locator('[data-slot="rear"]').click();
    await page.locator('[data-bind="card.skills.rear.condition"]').fill('HP50%以下の味方がいる');
    await page.locator('[data-action="add-effect"]').click();
    await page.locator('[data-bind="card.skills.rear.effects.1.typeId"]').selectOption('buff');
    await page.locator('[data-bind="card.skills.rear.effects.1.stat"]').selectOption('armor');
    await page.locator('[data-action="target-preset"][data-index="1"][data-preset="self"]').click();
    await page.locator('[data-bind="card.skills.rear.effects.1.amount.mode"]').selectOption('fixed');
    await page.locator('[data-bind="card.skills.rear.effects.1.amount.value"]').fill('5');
    await page.locator('[data-bind="card.skills.rear.effects.1.duration.mode"]').selectOption('turns');
    await page.locator('[data-bind="card.skills.rear.effects.1.details"]').fill('装甲を付与');
    await page.locator('[data-action="move-effect"][data-index="1"][data-direction="up"]').click();
    assert.equal(await page.locator('[data-bind="card.skills.rear.effects.0.typeId"]').inputValue(),'buff');
    assert.equal(await page.locator('[data-action="add-effect"]').isDisabled(),true);
    await page.locator('[data-effect-index="0"] details').last().locator('summary').click();
    await page.locator('[data-bind="card.skills.rear.effects.0.alternate.condition"]').fill('得意地形');
    await page.locator('[data-bind="card.skills.rear.effects.0.alternate.amount"]').fill('10');
    assert.match(await page.locator('#preview').textContent(),/強化（装甲）：5（得意地形：10） \/ 2T/);
    assert.equal(await page.locator('[data-effect-index="0"] [data-cell="5"][data-side="ally"]').getAttribute('aria-pressed'),'true');
    assert.equal(await page.locator('[data-effect-index="0"] .origin').getAttribute('data-cell'),'5');
    checks.push('二効果の上限・順序・相対対象・条件別量・持続T');
    await page.locator('[data-action="new-definition"]').first().click();
    await page.locator('#definition-form [name="name"]').fill('結界付与');await page.locator('#definition-form [name="id"]').fill('ward');
    await page.locator('#definition-form [name="description"]').fill('専用の結界を与える設計定義');
    await page.locator('[data-action="add-parameter"]').click();
    await page.locator('[data-param="label"]').fill('結界名');await page.locator('[data-param="key"]').fill('wardName');
    await page.locator('#definition-form button[type="submit"]').click();
    assert.equal(await page.locator('#dialog').evaluate(el=>el.open),false,await page.locator('#dialog').evaluate(el=>JSON.stringify([...el.querySelectorAll('input,textarea,select')].map(x=>({name:x.name,value:x.value,valid:x.validity.valid,message:x.validationMessage}))))+errors.join('\n'));
    await page.locator('[data-bind="card.skills.rear.effects.0.typeId"]').selectOption('ward');
    await page.locator('[data-bind="card.skills.rear.effects.0.params.wardName"]').fill('苔の結界');
    assert.match(await page.locator('#preview').textContent(),/結界名：苔の結界/);
    await page.locator('[data-tab="notes"]').click();
    await page.locator('[data-bind="notes.intent"]').fill('低コストで前衛の持久力を補う。開発用メモ。');
    await page.locator('[data-bind="notes.usage"]').fill('後衛から味方前衛を回復する。');
    await page.locator('[data-bind="tags"]').fill('回復, 低コスト');
    await page.locator('[data-tab="history"]').click();
    await page.locator('[data-log="reason"]').fill('初期案を作成');
    await page.locator('[data-log="result"]').fill('戦闘検証はまだ行っていない');
    await page.locator('#save').click();await page.locator('#save-state').filter({hasText:'保存済み'}).waitFor();
    let saved=JSON.parse(await fs.readFile(path.join(dataDir,'library.json'),'utf8'));M.validateLibrary(saved);
    assert.equal(saved.cards[0].notes.intent,'低コストで前衛の持久力を補う。開発用メモ。');assert.equal(saved.cards[0].history[0].reason,'初期案を作成');
    assert.equal(saved.definitions[0].parameters[0].key,'wardName');
    checks.push('新効果定義と専用項目の作成・設計メモと履歴のファイル保存');
    await page.reload();await page.locator('#save-state').filter({hasText:'接続'}).waitFor();
    assert.match(await page.locator('#preview').textContent(),/結界名：苔の結界/);
    const specDownload=page.waitForEvent('download');await page.locator('[data-action="export-card"]').click();
    const spec=JSON.parse(await fs.readFile(await (await specDownload).path(),'utf8'));assert.ok(!JSON.stringify(spec).includes('開発用メモ'));assert.equal(spec.format,'card-design-spec');
    const backupDownload=page.waitForEvent('download');await page.locator('#export-library').click();
    const backupPath=await (await backupDownload).path();const backup=JSON.parse(await fs.readFile(backupPath,'utf8'));M.validateLibrary(backup);
    await page.locator('#json-file').setInputFiles(backupPath);assert.equal(await page.locator('.library-card').count(),1);
    await page.locator('#json-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":2}')});assert.match(await page.locator('#notice').textContent(),/取り込めません/);
    await page.locator('#save').click();await page.locator('#save-state').filter({hasText:'保存済み'}).waitFor();
    checks.push('再読込・メモを除く仕様JSON・DB書出し取込・不正取込の保持');
    await page.locator('[data-tab="basic"]').click();await page.getByLabel('AT',{exact:true}).fill('45');await page.keyboard.press('Control+s');await page.locator('#save-state').filter({hasText:'保存済み'}).waitFor();
    await page.locator('[data-tab="history"]').click();assert.match(await page.locator('.timeline').textContent(),/card.at/);
    const backupFiles=await fs.readdir(path.join(dataDir,'backups'));assert.ok(backupFiles.length>=2);
    await page.locator('[data-action="duplicate"]').click();assert.equal(await page.locator('.library-card').count(),2);
    await page.locator('#search').fill('低コスト');assert.equal(await page.locator('.library-card').count(),2);await page.locator('#search').fill('見つからない語');assert.equal(await page.locator('.library-card').count(),0);await page.locator('#search').fill('');
    await page.locator('#search').fill('戦闘検証はまだ行っていない');assert.equal(await page.locator('.library-card').count(),1);await page.locator('#search').fill('');
    await page.getByLabel('カード名',{exact:true}).fill('<img src=x onerror="window.xss=1">');assert.equal(await page.locator('.preview-core>h2 img').count(),0);assert.equal(await page.evaluate(()=>window.xss),undefined);await page.getByLabel('カード名',{exact:true}).fill('苔庭の守り手・別案');
    checks.push('差分履歴・Ctrl+S・保存前バックアップ・複製・メモ検索・HTML文字の無害表示');
    await page.locator('#save').click();await page.locator('#save-state').filter({hasText:'保存済み'}).waitFor();
    await page.locator('[data-tab="effects"]').click();await page.locator('[data-slot="rear"]').click();
    for(const [name,width,height] of [['desktop',1440,1000],['tablet',820,1180],['mobile',390,844],['small',320,568]]) {
      await page.setViewportSize({width,height});await page.evaluate(()=>window.scrollTo(0,0));
      const sizes=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert.ok(sizes.scroll<=sizes.width,`${name} 横はみ出し ${JSON.stringify(sizes)}`);
      await page.screenshot({path:path.join(artifactDir,`${name}.png`),fullPage:name==='mobile'});
      if(name==='mobile') {
        const cell=page.locator('[data-effect-index="0"] [data-cell="3"][data-side="ally"]');
        await cell.tap();assert.equal(await cell.getAttribute('aria-pressed'),'true');await cell.tap();
        await page.getByRole('button',{name:'結界付与の説明',exact:true}).tap();assert.match(await page.locator('#dialog-body').textContent(),/専用の結界/);await page.keyboard.press('Escape');
      }
    }
    checks.push('実Edgeで1440/820/390/320pxの表示・390pxのタップ操作');
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('#save').click();await page.locator('#save-state').filter({hasText:'保存済み'}).waitFor();
    saved=JSON.parse(await fs.readFile(path.join(dataDir,'library.json'),'utf8'));
    const serverChange=M.clone(saved);serverChange.cards[0].card.ag=99;
    await fetch(url+'/api/library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(serverChange)});
    await page.locator('[data-tab="basic"]').click();await page.getByLabel('HP',{exact:true}).fill('111');await page.locator('#save').click();await page.locator('#notice').filter({hasText:'別の画面'}).waitFor();
    assert.equal(await page.getByLabel('HP',{exact:true}).inputValue(),'111');
    const conflicted=JSON.parse(await fs.readFile(path.join(dataDir,'library.json'),'utf8'));assert.equal(conflicted.cards[0].card.ag,99);
    checks.push('競合保存を拒否し、編集中の内容を画面に保持');
    assert.deepEqual(errors,[]);
    await fs.writeFile(path.join(artifactDir,'results.json'),JSON.stringify({passed:true,checks,errors,temporaryDataDir:dataDir},null,2));
    console.log(JSON.stringify({passed:true,checks:checks.length,artifacts:artifactDir,temporaryDataDir:dataDir},null,2));
  } finally {await browser?.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
